# Generated by Django 4.1.7 on 2023-02-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirtyimage',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
